version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: surfshop-postgres
    environment:
      POSTGRES_DB: surfshop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
