spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/surfshop
    username: user
    password: pass
    hikari:
      initialization-fail-timeout: 10000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.default_schema: public

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true

server:
  port: 8080
  
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.amqp.rabbit: DEBUG
 


cors:
  allowed-origin: ${CORS_ALLOWED_ORIGIN:*}
