spring:
  profiles:
    default: prod

server:
  address: 0.0.0.0
  port: 8080

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.flywaydb: DEBUG

cors:
  allowed-origin: ${CORS_ALLOWED_ORIGIN:*}

management:
  endpoints:
    web:
      exposure:
        include: health

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/surfshop}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:pass}
    hikari:
      initialization-fail-timeout: 10000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.default_schema: surfshop

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: surfshop
    defaultSchema: surfshop

management:
  health:
    db:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: keepalive

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  flyway:
    enabled: false

management:
  health:
    db:
      enabled: false


---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/surfshop}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:pass}



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.default_schema: public

  flyway:
    enabled: false
